# Form implementation generated from reading ui file '1/calk_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(444, 262)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.addButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(260, 60, 75, 71))
        self.addButton.setObjectName("addButton")
        self.subtractButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.subtractButton.setGeometry(QtCore.QRect(260, 140, 75, 71))
        self.subtractButton.setObjectName("subtractButton")
        self.multiplyButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.multiplyButton.setGeometry(QtCore.QRect(340, 60, 75, 71))
        self.multiplyButton.setObjectName("multiplyButton")
        self.divideButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.divideButton.setGeometry(QtCore.QRect(340, 140, 75, 71))
        self.divideButton.setObjectName("divideButton")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 80, 163, 56))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setText("a=")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_a = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_a.setObjectName("lineEdit_a")
        self.horizontalLayout_2.addWidget(self.lineEdit_a)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setText("b=")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_b = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_b.setObjectName("lineEdit_b")
        self.horizontalLayout.addWidget(self.lineEdit_b)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.result = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.result.setGeometry(QtCore.QRect(21, 151, 231, 41))
        self.result.setObjectName("result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addButton.setText(_translate("MainWindow", "Сложение"))
        self.subtractButton.setText(_translate("MainWindow", "Вычитание"))
        self.multiplyButton.setText(_translate("MainWindow", "Умножение"))
        self.divideButton.setText(_translate("MainWindow", "Деление"))
